"""add fcm_token to users

Revision ID: 673eb06237ff
Revises: 599664fd1024
Create Date: 2026-05-30 10:37:40.162527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673eb06237ff'
down_revision = '599664fd1024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fcm_token')

    # ### end Alembic commands ###
